export const GET_COUNTRY_START = "GET_COUNTRY_START";
export const GET_COUNTRY_SUCCESS = "GET_COUNTRY_SUCCESS";
export const GET_COUNTRY_FAILURE = "GET_COUNTRY_FAILURE";
export const DEFINE_SELECTED_COUNTRY = "DEFINE_SELECTED_COUNTRY";
